apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: llamastack
  namespace: lls-demo
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: GRANITE_VLLM
          value: 'https://litellm-prod.apps.maas.redhatworkshops.io/v1'
        - name: GRANITE_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: granite_token
        - name: TAVILY_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: tavily_key
      name: llama-stack
      port: 8321
    distribution:
      name: remote-vllm
    userConfig:
      configMapName: llama-stack-config
